# Generated by Django 4.1.5 on 2023-01-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=30)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="venue",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
