# Generated by Django 4.1.5 on 2023-01-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_rename_category_name_agecategory_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
