# Generated by Django 4.1.5 on 2023-01-25 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_remove_team_age_category"),
        ("matches", "0005_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "date_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, max_length=1024)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "age_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matches.agecategory",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="away_team",
                        to="teams.team",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matches.competition",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_team",
                        to="teams.team",
                    ),
                ),
                (
                    "referee_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referee_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referee_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matches.season",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matches.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["date_time"],
            },
        ),
    ]
