# Generated by Django 4.1.5 on 2023-01-30 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competitions", "0001_initial"),
        ("matches", "0006_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="age_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="competitions.agecategory",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="competitions.competition",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="competitions.season",
            ),
        ),
        migrations.DeleteModel(
            name="AgeCategory",
        ),
        migrations.DeleteModel(
            name="Competition",
        ),
        migrations.DeleteModel(
            name="Season",
        ),
        migrations.AddField(
            model_name="gameapplication",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matches.game"
            ),
        ),
        migrations.AddField(
            model_name="gameapplication",
            name="ref_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
