# Generated by Django 4.1.5 on 2023-01-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_agecategory_venue_last_updated"),
        ("teams", "0002_team_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="age_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matches.agecategory",
            ),
        ),
    ]
